// ===== DADOS REVERSALOG =====
// Extraído de: Quadro_Equipe_Logistica_Reversa.xlsx
// Data: 2026-05-21
// Lojas: 90 | Produtos: 13 | Colaboradores: 42

const REVERSALOG_DATA = {
    lojas: [
        {"numero": 1, "nome": "CAROLINA", "codigo": 1},
        {"numero": 2, "nome": "PONTE PRETA", "codigo": 6},
        {"numero": 3, "nome": "BONFIM", "codigo": 7},
        {"numero": 4, "nome": "AMOREIRAS", "codigo": 9},
        {"numero": 5, "nome": "AMERICANA", "codigo": 10},
        {"numero": 6, "nome": "ANALÂNDIA", "codigo": 11},
        {"numero": 7, "nome": "ANDRADINA", "codigo": 12},
        {"numero": 8, "nome": "ARARAQUARA", "codigo": 13},
        {"numero": 9, "nome": "ARARAS", "codigo": 14},
        {"numero": 10, "nome": "ARTUR NOGUEIRA", "codigo": 15},
        {"numero": 11, "nome": "ATIBAIA", "codigo": 16},
        {"numero": 12, "nome": "BARÃO DE ANTONINA", "codigo": 17},
        {"numero": 13, "nome": "BARIRI", "codigo": 18},
        {"numero": 14, "nome": "BARRETOS", "codigo": 19},
        {"numero": 15, "nome": "BAURU", "codigo": 20},
        {"numero": 16, "nome": "BEBEDOURO", "codigo": 21},
        {"numero": 17, "nome": "BOM SUCESSO DE ITARARÉ", "codigo": 22},
        {"numero": 18, "nome": "BOREBI", "codigo": 23},
        {"numero": 19, "nome": "BORBOREMA", "codigo": 24},
        {"numero": 20, "nome": "BOTUCATU", "codigo": 25},
        {"numero": 21, "nome": "BRAGANÇA PAULISTA", "codigo": 26},
        {"numero": 22, "nome": "BROTAS", "codigo": 27},
        {"numero": 23, "nome": "CABREUVA", "codigo": 28},
        {"numero": 24, "nome": "CACONDE", "codigo": 29},
        {"numero": 25, "nome": "CAÇAPAVA", "codigo": 30},
        {"numero": 26, "nome": "CACHOEIRA PAULISTA", "codigo": 31},
        {"numero": 27, "nome": "CAJAMAR", "codigo": 32},
        {"numero": 28, "nome": "CAJURU", "codigo": 33},
        {"numero": 29, "nome": "CAMPINAS", "codigo": 34},
        {"numero": 30, "nome": "CAMPO LIMPO PAULISTA", "codigo": 35},
        {"numero": 31, "nome": "CANDIDO MOTA", "codigo": 36},
        {"numero": 32, "nome": "CANITAR", "codigo": 37},
        {"numero": 33, "nome": "CAPÃO BONITO", "codigo": 38},
        {"numero": 34, "nome": "CARAGUATATUBA", "codigo": 39},
        {"numero": 35, "nome": "CARAPICUIBA", "codigo": 40},
        {"numero": 36, "nome": "CARDOSO", "codigo": 41},
        {"numero": 37, "nome": "CASA BRANCA", "codigo": 42},
        {"numero": 38, "nome": "CASTILHO", "codigo": 43},
        {"numero": 39, "nome": "CATANDUVA", "codigo": 44},
        {"numero": 40, "nome": "CATIGUÁ", "codigo": 45},
        {"numero": 41, "nome": "CEDRAL", "codigo": 46},
        {"numero": 42, "nome": "CERQUEIRA CESAR", "codigo": 47},
        {"numero": 43, "nome": "CERQUILHO", "codigo": 48},
        {"numero": 44, "nome": "CESAR DE SOUSA", "codigo": 49},
        {"numero": 45, "nome": "CHARQUEADA", "codigo": 50},
        {"numero": 46, "nome": "CHAVANTES", "codigo": 51},
        {"numero": 47, "nome": "CLEMENTINA", "codigo": 52},
        {"numero": 48, "nome": "COLINA", "codigo": 53},
        {"numero": 49, "nome": "COLÔMBIA", "codigo": 54},
        {"numero": 50, "nome": "CONCHAL", "codigo": 55},
        {"numero": 51, "nome": "CONCHAS", "codigo": 56},
        {"numero": 52, "nome": "CORBÉLIA", "codigo": 57},
        {"numero": 53, "nome": "COROADOS", "codigo": 58},
        {"numero": 54, "nome": "CORONEL MACEDO", "codigo": 59},
        {"numero": 55, "nome": "CORUMBATAÍ", "codigo": 60},
        {"numero": 56, "nome": "COSMÓPOLIS", "codigo": 61},
        {"numero": 57, "nome": "COSMORAMA", "codigo": 62},
        {"numero": 58, "nome": "COTIA", "codigo": 63},
        {"numero": 59, "nome": "CRUZEIRO", "codigo": 64},
        {"numero": 60, "nome": "CUBATÃO", "codigo": 65},
        {"numero": 61, "nome": "CUNHA", "codigo": 66},
        {"numero": 62, "nome": "CURUCUTU", "codigo": 67},
        {"numero": 63, "nome": "DESCALVADO", "codigo": 68},
        {"numero": 64, "nome": "DIADEMA", "codigo": 69},
        {"numero": 65, "nome": "DIVINOLÂNDIA", "codigo": 70},
        {"numero": 66, "nome": "DOBRADA", "codigo": 71},
        {"numero": 67, "nome": "DOCEZINHOS", "codigo": 72},
        {"numero": 68, "nome": "DOIS CÓRREGOS", "codigo": 73},
        {"numero": 69, "nome": "DOLCINÓPOLIS", "codigo": 74},
        {"numero": 70, "nome": "DOURADO", "codigo": 75},
        {"numero": 71, "nome": "DRACENA", "codigo": 76},
        {"numero": 72, "nome": "DUARTINA", "codigo": 77},
        {"numero": 73, "nome": "DUMONT", "codigo": 78},
        {"numero": 74, "nome": "ECHAPORÃ", "codigo": 79},
        {"numero": 75, "nome": "ELDORADO", "codigo": 80},
        {"numero": 76, "nome": "ELIAS FAUSTO", "codigo": 81},
        {"numero": 77, "nome": "ELSINOR", "codigo": 82},
        {"numero": 78, "nome": "EMBAÚBA", "codigo": 83},
        {"numero": 79, "nome": "EMBU", "codigo": 84},
        {"numero": 80, "nome": "EMBU-GUAÇU", "codigo": 85},
        {"numero": 81, "nome": "EMILIANÓPOLIS", "codigo": 86},
        {"numero": 82, "nome": "ENGENHEIRO COELHO", "codigo": 87},
        {"numero": 83, "nome": "ESPÍRITO SANTO DO PINHAL", "codigo": 88},
        {"numero": 84, "nome": "ESTIVA GERBI", "codigo": 89},
        {"numero": 85, "nome": "ESTRELINHA", "codigo": 90},
        {"numero": 86, "nome": "ESTRELA DO NORTE", "codigo": 91},
        {"numero": 87, "nome": "ESTRÊLA DO OESTE", "codigo": 92},
        {"numero": 88, "nome": "ESTROMBA", "codigo": 93},
        {"numero": 89, "nome": "ETAPEVA", "codigo": 94},
        {"numero": 90, "nome": "IBATÉ", "codigo": 95}
    ],
    
    produtos: [
        {"nome": "CARADORI", "codigo": "164059"},
        {"nome": "CAIXA PLASTICA MODELO P", "codigo": "213662"},
        {"nome": "CAIXA PLASTICA MODELO G", "codigo": "213659"},
        {"nome": "CAIXA PLASTICA MODELO M", "codigo": "215566"},
        {"nome": "CX FORNECEDOR", "codigo": "CXF"},
        {"nome": "PALETE PBR", "codigo": "184345"},
        {"nome": "PALETE CHEP", "codigo": "184346"},
        {"nome": "PALLET DESCARTAVEL", "codigo": "PD"},
        {"nome": "GAIOLA", "codigo": "GAIOLA"},
        {"nome": "PALETE EURO", "codigo": ""},
        {"nome": "PALETE EURO CHEP", "codigo": ""},
        {"nome": "CARRINHO DE FLOR", "codigo": "CF"},
        {"nome": "STRETCH", "codigo": "149345"}
    ],
    
    colaboradores: [
        {"matricula": "01790206", "nome": "ALBERTINO DOS SANTOS PRETO", "cargo": "OPERADOR DE LOGÍSTICA II", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201073", "nome": "ANTONIO JOSE SILVA DE OLIVEIRA", "cargo": "AUXILIAR DE HIGIENIZAÇÃO II", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201061", "nome": "CESAR VINICIOS THOMAZ ALVES DOS SANTOS", "cargo": "CONFERENTE I", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201736", "nome": "DANIEL RODRIGUES DA SILVA", "cargo": "AUXILIAR DE HIGIENIZAÇÃO", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201704", "nome": "DIEGO DE MELO CARDOSO", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201539", "nome": "EDSON ALVES PEREIRA", "cargo": "OPERADOR DE LOGÍSTICA I", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201647", "nome": "FABIO SANTOS OLIVEIRA", "cargo": "CONFERENTE II", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201081", "nome": "FERNANDO JOSE SILVA", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201722", "nome": "FRANCISCO PEREIRA SANTOS", "cargo": "AUXILIAR DE HIGIENIZAÇÃO", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201605", "nome": "GILSON OLIVEIRA SANTOS", "cargo": "OPERADOR DE LOGÍSTICA II", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201691", "nome": "GUSTAVO SILVA COSTA", "cargo": "CONFERENTE I", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201563", "nome": "HENRIQUE ALVES GOMES", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201809", "nome": "HUMBERTO CARLOS SILVA", "cargo": "AUXILIAR DE HIGIENIZAÇÃO II", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201418", "nome": "IGOR SANTOS OLIVEIRA", "cargo": "OPERADOR DE LOGÍSTICA I", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201756", "nome": "ISADORE PEREIRA SANTOS", "cargo": "CONFERENTE II", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201484", "nome": "JAIME SILVA COSTA", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201635", "nome": "JAILTON OLIVEIRA SANTOS", "cargo": "AUXILIAR DE HIGIENIZAÇÃO", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201569", "nome": "JANEIRO ALVES GOMES", "cargo": "OPERADOR DE LOGÍSTICA II", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201743", "nome": "JAQUES SANTOS OLIVEIRA", "cargo": "CONFERENTE I", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201807", "nome": "JARBAS SILVA COSTA", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201621", "nome": "JARDEL OLIVEIRA SANTOS", "cargo": "AUXILIAR DE HIGIENIZAÇÃO II", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201475", "nome": "JAYME ALVES GOMES", "cargo": "OPERADOR DE LOGÍSTICA I", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201593", "nome": "JERONIMO SANTOS OLIVEIRA", "cargo": "CONFERENTE II", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201428", "nome": "JOBSON SILVA COSTA", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201712", "nome": "JOCELINO OLIVEIRA SANTOS", "cargo": "AUXILIAR DE HIGIENIZAÇÃO", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201536", "nome": "JODILSON ALVES GOMES", "cargo": "OPERADOR DE LOGÍSTICA II", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201664", "nome": "JOELSON SANTOS OLIVEIRA", "cargo": "CONFERENTE I", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201409", "nome": "JOKÉBA SILVA COSTA", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201728", "nome": "JOLIVETE OLIVEIRA SANTOS", "cargo": "AUXILIAR DE HIGIENIZAÇÃO II", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201577", "nome": "JONATAS ALVES GOMES", "cargo": "OPERADOR DE LOGÍSTICA I", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201651", "nome": "JONILSON SANTOS OLIVEIRA", "cargo": "CONFERENTE II", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201495", "nome": "JONIVAL SILVA COSTA", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201613", "nome": "JONIVALDO OLIVEIRA SANTOS", "cargo": "AUXILIAR DE HIGIENIZAÇÃO", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201772", "nome": "JORIVALDO ALVES GOMES", "cargo": "OPERADOR DE LOGÍSTICA II", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201547", "nome": "JOSELSON SANTOS OLIVEIRA", "cargo": "CONFERENTE I", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201629", "nome": "JOSENILDO SILVA COSTA", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201741", "nome": "JOSÉLIO OLIVEIRA SANTOS", "cargo": "AUXILIAR DE HIGIENIZAÇÃO II", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201508", "nome": "JOZADAQUE ALVES GOMES", "cargo": "OPERADOR DE LOGÍSTICA I", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201673", "nome": "JOZIMAR SANTOS OLIVEIRA", "cargo": "CONFERENTE II", "turno": "LOG Reversa Equipe T2"},
        {"matricula": "02201586", "nome": "JUCELINO SILVA COSTA", "cargo": "OPERADOR DE CARGA E DESCARGA", "turno": "LOG Reversa Equipe T3"},
        {"matricula": "02201759", "nome": "JUCINEI OLIVEIRA SANTOS", "cargo": "AUXILIAR DE HIGIENIZAÇÃO", "turno": "LOG - Reversa Equipe"},
        {"matricula": "02201427", "nome": "JUDSON ALVES GOMES", "cargo": "OPERADOR DE LOGÍSTICA II", "turno": "LOG Reversa Equipe T2"}
    ],
    
    meta: {
        lojas_total: 90,
        produtos_total: 13,
        colaboradores_total: 42,
        timestamp: "2026-05-21T09:43:00"
    }
};